### ISSUE TITLE
Please, make your examples working out of the box

### ISSUE THREAD

**Issue by frol** [gmr/rejected#12]
You have `example.py` inside a package (it is OK, though I haven't seen such examples, and usually I like to play with examples myself and it is a bit awkward to modify files in a package), and there are two `example.py` in the documentation and README with little information on how to actually run it. There are also 3 versions of `example.yaml` and again zero information about them.

It would be much better to have only one example, but covered from the very beginning:
- [ ] Example project structure with all necessary files (`example.yaml` + `example.py` or `example/__init__.py`)
- [ ] Fix logging settings in `example.yaml`, so your example with `LOGGER.info()` would actually print anything out of the box (or release `helper==2.4.2`)
- [ ] Instructions on how to run an example daemon (`rejected -c example.yaml -p "$(pwd)"` - this is how I am running it now)
- [ ] Client example will be also super helpful
- [ ] Other best practices.

**Comment by sieben** [comment]
Also on modern ubuntu which are quite common, /var/run/syslog is now /var/run/systemd/journal/syslog

**Comment by nvllsvm** [comment]
Here's a minimal example of using Rejected to consume messages. It should *just work* without any setup beyond having the rejected package installed.
https://github.com/nvllsvm/rejected_example

**Comment by gmr** [comment]
Added full detailed walk-through as part of the 4.0 docs and examples.
