### ISSUE TITLE
https://rejected.readthedocs.io is broken

### ISSUE THREAD

**Issue by nvllsvm** [gmr/rejected#22]
https://rejected.readthedocs.io redirects to https://rejected.readthedocs.io/en/stable/ which is not rejected's documentation - the following is shown:

![image](https://user-images.githubusercontent.com/6550543/33329326-472e7fc8-d42a-11e7-8aca-3d848b2716ad.png)

This impacts documentation present in the README.

https://rejected.readthedocs.io/en/latest/ is functional.

**Comment by gmr** [comment]
Thanks
