### ISSUE TITLE
Consumer.on_finish is only called when ACK'ing

### ISSUE THREAD

**Issue by dave-shawley** [gmr/rejected#24]
https://github.com/gmr/rejected/blob/974c126984758d65dafa64282781bb41621a34b1/rejected/consumer.py#L1044-L1045

I think that the guarantee should be that if `prepare` completes, then `on_finish` should be called.

**Comment by gmr** [comment]
Will be addressed in 4.0:

https://github.com/gmr/rejected/commit/db241166d4208c9d6fd0a9e9f16396aa68c3abe0#diff-5f2c460ddbbaeb282336d6fac50b2d5dR1012
