### ISSUE TITLE
Update configuration example ssl configuration

### ISSUE THREAD

**Issue by bmfredrick** [gmr/rejected#44]
The configuration example at https://rejected.readthedocs.io/en/stable/example_config.html is still using the old ssl configuration instead of the newer ssl_options configuration.  This can be confusing to users who are copying the example as a starting point for their own project configuration.  Please update the example to be accurate with the project's API.

ssl_options documentation: https://rejected.readthedocs.io/en/stable/configuration.html#ssl-options

Screenshot:
![image](https://user-images.githubusercontent.com/1956901/208160631-4ebbcb5f-5825-4458-909a-0b3d4bb7a9ae.png)

**Comment by gmr** [comment]
Example added, will be published with 4.0 release.
